name: shape_of_view
description: Give a custom shape to any flutter widget, Material Design 2 ready
version: 2.0.0
authors:
  - Arnaud DA SILVA <danaru@tuta.io>
  - Charly CAULET <contact@charly-caulet.net>
homepage: https://github.com/UPrefer/Flutter-ShapeOfView

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ^2.0.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
